---

- name: Install Chromium
  apt:
    name: chromium-browser
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"

# See https://www.chromium.org/administrators/policy-list-3
- name: Create Chromium policies directory for all users
  file:
    path: /etc/chromium/policies/managed
    state: directory

- name: Create Chromium JSON policy file to force settings for all users
  copy:
    src: policy.json
    dest: "/etc/chromium/policies/managed/benoth-policy.json"

- name: Create Chromium extensions directory for all users
  file:
    path: /usr/share/chromium-browser/extensions
    state: directory

# See https://developer.chrome.com/extensions/external_extensions#preferences
- name: Create Chromium JSON file to install extensions for all users
  template:
    src: chrome-extensions.json.j2
    dest: "/usr/share/chromium-browser/extensions/{{ item }}.json"
  with_items:
    - cjpalhdlnbpafiamejdnhcphjbkeiagm # ublock
    - ajpgkpeckebdhofmmjfgcjjiiejpodla # Xmarks Bookmark Sync
    - bcjindcccaagfpapjjmafapmmgkkhgoa # JSON Formatter
    - miefikpgahefdbcgoiicnmpbeeomffld # Blackfire Companion
    - fjnbnpbmkenffdnngjfgmeleoegfcffe # Stylish
    # - jbbplnpkjmmeebjpijfedlgcdilocofh # wave-evaluation-tool
    # - idgpnmonknjnojddfkpgkljpfnnfcklj # ModHeader
    # - jgbbilmfbammlbbhmmgaagdkbkepnijn # Cookie Inspector
    # - dapjbgnjinbpoindlpdmhochffioedbn # builtwith-technology-prof
    # - deoaddaobnieaecelinfdllcgdehimih # kimono
    # - fhbjgbiflinjbdggehcddcbncdddomop # postman
