---

- name: Check if MySQL WorkBench is installed
  command: dpkg-query -W mysql-workbench
  register: mysql_workbench_check_deb
  failed_when: mysql_workbench_check_deb.rc > 1
  changed_when: mysql_workbench_check_deb.rc == 1

- name: Download MySQL WorkBench
  get_url: url="http://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-6.3.8-1ubu1604-amd64.deb" dest="/tmp/download-mysql-workbench-latest.deb"
  when: mysql_workbench_check_deb.rc == 1

- name: Install MySQL WorkBench
  apt: deb="/tmp/download-mysql-workbench-latest.deb"
  when: mysql_workbench_check_deb.rc == 1

- name: Clean MySQL WorkBench deb file
  file: path=/tmp/download-mysql-workbench-latest.deb state=absent
